import os
from os import getenv
from dotenv import load_dotenv

load_dotenv()
admins = {}
SESSION_NAME = getenv("SESSION_NAME", "session")
BOT_TOKEN = getenv("BOT_TOKEN")
BOT_NAME = getenv("BOT_NAME")
API_ID = int(getenv("API_ID"))
API_HASH = getenv("API_HASH")
MONGODB_URL = getenv("MONGODB_URL")
OWNER_NAME = getenv("OWNER_NAME")
ALIVE_NAME = getenv("ALIVE_NAME")
BOT_USERNAME = getenv("BOT_USERNAME")
ASSISTANT_NAME = getenv("ASSISTANT_NAME")
GROUP_SUPPORT = getenv("GROUP_SUPPORT", "XxllllllllllllllllllllllllllxX")
UPDATES_CHANNEL = getenv("UPDATES_CHANNEL", "XxvprxX")
SUDO_USERS = list(map(int, getenv("SUDO_USERS").split()))
OWNER_ID = list(map(int, getenv("OWNER_ID").split()))
MONGODB_URL = getenv("MONGODB_URL")
COMMAND_PREFIXES = list(getenv("COMMAND_PREFIXES", "ح ف ب غ س ك و م ا ت / ! . ذ").split())
ALIVE_IMG = getenv("ALIVE_IMG", "https://t.me/UU_LE2")
DURATION_LIMIT = int(getenv("DURATION_LIMIT", "60"))
UPSTREAM_REPO = getenv("UPSTREAM_REPO")
IMG_1 = getenv("IMG_1", "https://t.me/UU_LE2")
IMG_2 = getenv("IMG_2", "https://t.me/UU_LE2")
IMG_3 = getenv("IMG_3", "https://t.me/UU_LE2")
IMG_4 = getenv("IMG_4", "https://t.me/UU_LE2")
IMG_5 = getenv("IMG_5", "https://t.me/UU_LE2")
